### ISSUE TITLE
Howe Lab Conversion

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/howe-lab-to-nwb#1]
# Fiber photometry and Imaging ([Vu 2024](https://www.sciencedirect.com/science/article/pii/S0896627323009704))

- [x] collect initial notes: #2 
- [x] ask for missing data
- [x] Add extractor and interface for Imaging (Hamamatsu .cdx file) (#5): integration with NeuroConv progress: https://github.com/catalystneuro/roiextractors/pull/338
- [x] Add motion corrected imaging data (_MC.tif file) https://github.com/catalystneuro/howe-lab-to-nwb/pull/6
- [x] Add the extracted fluorescence time series data (___ROIs.mat) in progress #4 
- [x] Annotate fibers (___fiber_locations.xlsx)
- [x] Add behavioral camera recordings as external file (https://github.com/catalystneuro/howe-lab-to-nwb/pull/7)
- [x] Add raw behavior file (___YYYY.MM.DD_hh.mm.ss.mat) -> using this to set the timestamps for imaging and fiber photometry from the TTL signal
- [x] Add preprocessed behavior file (___YYYY.MM.DD_hh.mm.ss_ttlInX_movieX.mat): the raw behavior data has been downsampled via block averaging to match the sampling rate of the neural data https://github.com/catalystneuro/howe-lab-to-nwb/pull/7
- [x] Add ROI masks and locations in a PlaneSegmentation table https://github.com/catalystneuro/howe-lab-to-nwb/pull/8
- [x] Enable multi-camera recordings #10 
- [x] Enable dual-wavelength excitation recordings https://github.com/catalystneuro/howe-lab-to-nwb/pull/9
- [x] Run conversion for example sessions
- [x] Run nwbinspector and fix issues
- [x] Create demo notebook (check Figures 4 and 5 in the manuscript) https://github.com/dandi/example-notebooks/pull/97
- [x] Create landing page for dataset on DANDI, populate with metadata from [the manuscript](https://www.sciencedirect.com/science/article/pii/S0896627323009704)
- [x] Upload to DANDI https://dandiarchive.org/dandiset/001084/draft

**Comment by weiglszonja** [comment]
For the meeting:

- They have the motion corrected image data, we need to ask if they also the x, y shifts (so that we can add this to a `MotionCorrection` object): https://github.com/HoweLab/MultifiberProcessing/blob/main/motion_correct.m#L356C1-L356C105 -> saving it to a .mat file https://github.com/HoweLab/MultifiberProcessing/blob/d7b33e23ed778c8c919ca90a21df0ade4b77f0e7/motion_correct.m#L356C1-L356C105

- starting time of motion corrected data should be aligned with the imaging data


- in cases where we have multiple avi files, how to automatically determine which TTL signal belongs to which avi file
